name: fb_cli_example
description: An example application command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

dependencies:

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  fb_cli:
    path: ../
